(global-activity-watch-mode)
(defun activity-watch-project-name-workspace-subdir ()
  (when (and (string-equal (activity-watch-project-name-projectile) "workspace")
	      default-directory)
    (let* ((project-name (activity-watch-project-name-projectile))
	   (project-root (projectile-project-root))
	   (relative-dir (file-relative-name default-directory project-root))
	   (subdir (nth 0 (split-string relative-dir "/"))))
      (unless (string-equal subdir ".") subdir)
      )))
(add-to-list 'activity-watch-project-name-resolvers 'workspace-subdir)
