;; diminish: hide some minor modes
(use-package delight)
(delight '(
	    (abbrev-mode " Abv" abbrev)
;           (smart-tab-mode " \\t" smart-tab)
;           (eldoc-mode nil "eldoc")
;           (rainbow-mode)
;           (overwrite-mode " Ov" t)
(emacs-lisp-mode "Elisp" :major)
;; (my-keys-mode " mK" "keys")
(my-keys-mode nil "keys")
(visual-line-mode nil "simple")
(buffer-face-mode nil "face-remap")
;; (org-cdlatex-mode " tex" "org")
(org-cdlatex-mode nil "org")
(undo-tree-mode nil "undo-tree")
(helm-mode nil "helm-mode")
(company-mode nil "company")
(which-key-mode nil "which-key")
(org-z-mode nil "org-z")
(activity-watch-mode nil)
(yas-minor-mode nil t)
(yas-global-mode nil t)
(eldoc-mode nil "eldoc")
))
