;; (load-library "orgmimerc")  ; requires wl ; does not work?
(use-package fontsrc)
;; (load-library "eafrc")
;; (load-library "activitywatchrc")
;; (load-library "badpersprc")
;; (load-library "goodpersprc")
;; ;; dired
;; (use-package helm)
(use-package diredrc)
;; (load-library "helmrc")
(use-package verticorc)
(use-package consultrc)
(use-package embarkrc) ;; after consult..
(use-package acerc)
(use-package projectsrc)
;; (load-library "cpprc")
;; (load-library "ya-cppref")
;; (setq ya-cppref-path-to-doc-root "/usr/share/cppreference/doc/html/")
;; (load-library "latexrc")
;; (load-library "lsprc")
(use-package condarc)
(use-package pythonrc)
(use-package eglotrc)
(use-package pytestrc)
(use-package pycellrc)
(use-package orgrc)
(use-package tanglerc)
(use-package evalueoxrc)
(use-package emamuxrc)
;; (load-library "einrc")
(use-package jupyterrc
  :config
  (jupyter-executable "~/anaconda3/bin/jupyter"))
;; ;; auto-complete
;; (load-library "autocompleterc")
(use-package completerc)
;; ;; zotero integration
;; (load-library "org-zotxt")
(use-package modelinerc)
(use-package diminishrc)
(use-package keys)
(use-package windowsrc)
(use-package hydrarc)
(use-package evrc)
(use-package imagesrc)
(use-package termrc)
(use-package term-tmuxrc)
(use-package vtermrc)
(use-package eshell-vterm)
(use-package ghostelrc)
(use-package copilotrc)
(use-package agentrc)
(use-package themerc)
