;; (load-library "orgmimerc")  ; requires wl ; does not work?
(require 'fontsrc)
;; (load-library "eafrc")
;; (load-library "activitywatchrc")
;; (load-library "badpersprc")
;; (load-library "goodpersprc")
;; ;; dired
;; (require 'helm)
(require 'diredrc)
;; (load-library "helmrc")
(require 'verticorc)
(require 'consultrc)
(require 'embarkrc) ;; after consult..
(require 'acerc)
(require 'projectsrc)
;; (load-library "cpprc")
;; (load-library "ya-cppref")
;; (setq ya-cppref-path-to-doc-root "/usr/share/cppreference/doc/html/")
;; (load-library "latexrc")
;; (load-library "lsprc")
(require 'condarc)
(require 'pythonrc)
(require 'eglotrc)
(require 'pytestrc)
(require 'pycellrc)
(require 'orgrc)
(require 'tanglerc)
(require 'evalueoxrc)
(require 'emamuxrc)
;; (load-library "einrc")
(use-package jupyterrc
  :custom
  (jupyter-executable "~/anaconda3/bin/jupyter"))
;; ;; auto-complete
;; (load-library "autocompleterc")
(require 'completerc)
;; ;; zotero integration
;; (load-library "org-zotxt")
(require 'modelinerc)
(require 'diminishrc)
(require 'keys)
(require 'windowsrc)
(require 'hydrarc)
(require 'evrc)
(require 'variousrc)
(require 'imagesrc)
(require 'termrc)
(require 'term-tmuxrc)
(require 'vtermrc)
(require 'eshell-vterm)
(require 'ghostelrc)
(require 'copilotrc)
(require 'agentrc)
(require 'themerc)
