(use-package fontsrc)
(use-package variousrc)
(require 'general)
;; lisp configuration files
;; (require 'helmrc)
(require 'keys)
(require 'windowsrc)
(require 'diminishrc)
(require 'diredrc)
(require 'eglotrc)
(require 'hydrarc)
(require 'imagesrc)
(require 'latexrc)
;; (require 'texify)
(require 'jupyterrc) ;; specify jupyterlab exec!
(require 'completerc)
(require 'verticorc)
(require 'copilotrc)
(require 'orgrc)
(require 'tanglerc)
(require 'ghostelrc)
(require 'themerc)
